# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: pipeline1
  # vmImage: 'windows-latest'

variables:
  solution: '**/P1.2.4/P1Mvc/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud_service_connection'
    organization: 'sekoudosso0837'
    scannerMode: 'MSBuild'
    projectKey: 'sekoudosso0837_Pipeline0837'
    projectName: 'Pipeline0837'
- task: DotNetCoreCLI@2
  displayName: Build Project
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'

#you MUST have this task to get test code coverage results.
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coburtura/coverage.xml'

# - task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    zipAfterPublish: true
    
# - task: AzureRmWebAppDeployment@4
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(3877ae91-edb2-458d-936b-e62ed2289cdb)'
    appType: 'webApp'
    WebAppName: 'shoppingbay'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

